import { LicenseRequestStatus, LicenseStatus, SkillStatus, TradeStatus, ExecutionStatus } from '@prisma/client';
import { prisma } from '../db.js';
import * as input from '../types.js';

const DEFAULT_USER_ID = process.env.DEFAULT_USER_ID;
const AUTO_APPROVE = process.env.AUTO_APPROVE_SKILLS === 'true';

export const tools = {
  async search_skills(raw: unknown) { const p = input.searchSkillsInput.parse(raw ?? {}); const skills = await prisma.skill.findMany({ where: { status: SkillStatus.ACTIVE, category: p.category, skillType: p.skillType, executionMode: p.executionMode, OR: p.query ? [{ title: { contains: p.query, mode: 'insensitive' } }, { description: { contains: p.query, mode: 'insensitive' } }] : undefined }, take: p.limit, include: { seller: true, reviews: true } }); return { skills: skills.map((s) => ({ id: s.id, title: s.title, description: s.description, type: s.skillType, seller: s.seller.name, status: s.status, rating: s.reviews.length ? s.reviews.reduce((a, r) => a + r.rating, 0) / s.reviews.length : null })) }; },
  async get_skill(raw: unknown) { const p = input.getSkillInput.parse(raw); return prisma.skill.findUniqueOrThrow({ where: { id: p.skillId }, include: { versions: true, reviews: { include: { reviewer: true } }, seller: true } }); },
  async create_agent(raw: unknown) { const p = input.createAgentInput.parse(raw); if (!DEFAULT_USER_ID) throw new Error('DEFAULT_USER_ID required'); return prisma.agent.create({ data: { ownerId: DEFAULT_USER_ID, ...p } }); },
  async list_my_agents(raw: unknown) { const p = input.listMyAgentsInput.parse(raw); return prisma.agent.findMany({ where: { ownerId: p?.ownerId ?? DEFAULT_USER_ID ?? '' } }); },
  async create_skill(raw: unknown) { const p = input.createSkillInput.parse(raw); if (!DEFAULT_USER_ID) throw new Error('DEFAULT_USER_ID required'); return prisma.skill.create({ data: { sellerId: DEFAULT_USER_ID, ...p, status: AUTO_APPROVE ? SkillStatus.ACTIVE : SkillStatus.PENDING_REVIEW } }); },
  async request_skill_license(raw: unknown) { const p = input.requestSkillLicenseInput.parse(raw); return prisma.skillLicenseRequest.upsert({ where: { id: `req_${p.agentId}_${p.skillId}` }, create: { ...p }, update: { reason: p.reason, status: LicenseRequestStatus.PENDING } }).catch(() => prisma.skillLicenseRequest.create({ data: p })); },
  async approve_license_request(raw: unknown) { const p = input.approveLicenseRequestInput.parse(raw); const req = await prisma.skillLicenseRequest.update({ where: { id: p.licenseRequestId }, data: { status: LicenseRequestStatus.APPROVED, reviewedAt: new Date() } }); return prisma.skillLicense.upsert({ where: { agentId_skillId: { agentId: req.agentId, skillId: req.skillId } }, create: { agentId: req.agentId, skillId: req.skillId, status: LicenseStatus.ACTIVE }, update: { status: LicenseStatus.ACTIVE } }); },
  async create_skill_request(raw: unknown) { const p = input.createSkillRequestInput.parse(raw); return prisma.skillRequest.create({ data: p }); },
  async make_skill_offer(raw: unknown) { const p = input.makeSkillOfferInput.parse(raw); return prisma.skillOffer.create({ data: p }); },
  async propose_skill_trade(raw: unknown) { const p = input.proposeSkillTradeInput.parse(raw); return prisma.skillTrade.create({ data: p }); },
  async accept_skill_trade(raw: unknown) { const p = input.acceptSkillTradeInput.parse(raw); const trade = await prisma.skillTrade.update({ where: { id: p.tradeId }, data: { status: TradeStatus.ACCEPTED } }); await prisma.skillLicense.upsert({ where: { agentId_skillId: { agentId: trade.requestingAgentId, skillId: trade.requestedSkillId } }, create: { agentId: trade.requestingAgentId, skillId: trade.requestedSkillId, status: LicenseStatus.ACTIVE }, update: { status: LicenseStatus.ACTIVE } }); await prisma.skillLicense.upsert({ where: { agentId_skillId: { agentId: trade.targetAgentId, skillId: trade.offeredSkillId } }, create: { agentId: trade.targetAgentId, skillId: trade.offeredSkillId, status: LicenseStatus.ACTIVE }, update: { status: LicenseStatus.ACTIVE } }); return trade; },
  async run_skill(raw: unknown) { const p = input.runSkillInput.parse(raw); const license = await prisma.skillLicense.findUnique({ where: { agentId_skillId: { agentId: p.agentId, skillId: p.skillId } } }); if (!license || license.status !== LicenseStatus.ACTIVE) throw new Error('Active license required'); const skill = await prisma.skill.findUniqueOrThrow({ where: { id: p.skillId } }); const started = Date.now(); let output: any = null; let error: string | undefined; let status: ExecutionStatus = ExecutionStatus.SUCCEEDED; if (["MOCK", "PROMPT_TEMPLATE"].includes(skill.executionMode)) { output = { mock: true, note: `Mock execution for ${skill.title}`, echoedInput: p.input, result: { summary: 'Synthetic result for development.', confidence: 0.82 } }; } else { output = { mock: true, note: 'External execution not implemented yet.', mode: skill.executionMode }; }
    const execution = await prisma.skillExecution.create({ data: { agentId: p.agentId, skillId: p.skillId, input: p.input, output, error, status, durationMs: Date.now() - started, finishedAt: new Date(), isMock: true } });
    return execution;
  },
  async get_execution_history(raw: unknown) { const p = input.getExecutionHistoryInput.parse(raw); return prisma.skillExecution.findMany({ where: { agentId: p.agentId, skillId: p.skillId }, take: p.limit, orderBy: { createdAt: 'desc' } }); }
};
